export enum ReparationStatesEnum{
    INGRESO = 'INGRESO',
    EN_REVISION = 'EN REVISION',
    EN_REPARACION = 'EN REPARACION',
    EN_PRESUPUESTO = 'EN PRESUPUESTO',
    REPARADO = 'REPARADO',
    PAGADO = 'PAGADO',
    ENTREGADO = 'ENTREGADO',
    CANCELADO = 'CANCELADO'
}