USE MegaHerdtAPI
DECLARE @id as int;

SET @id = (SELECT ISNULL(MAX(Id),0) FROM Articles);
DBCC CHECKIDENT(Articles, RESEED, @id)
SET IDENTITY_INSERT [dbo].[Articles] ON
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1, 2, 2,          N'SAM-MON-Monitor Led VeintiCuatroPulgadas', N'Monitor Led VeintiCuatroPulgadas', N'https://localhost:7032/articles/fc4430c7-f771-432f-a002-6851b2bb5d7c.webp', 86999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 3, 1002, 2,       N'LG -MON-Monitor LCD veintitrescomaochopulgadas', N'Monitor LCD veintitrescomaochopulgadas', N'https://localhost:7032/articles/acd7d413-1cbe-41f2-8c0e-ba78c46e449f.webp', 73599, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=3);
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 4, 1004, 2,       N'PHI-MON-Monitor LCD dieciochopulgasymedia', N'Monitor LCD dieciochopulgasymedia', N'https://localhost:7032/articles/8a2e8586-e578-4d45-87d3-e68d16b5d5cb.webp', 40799, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=4)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 6, 1003, 2,       N'HP -MON-Monitor IPS veintiunpulgadasymedia', N'Monitor IPS veintiunpulgadasymedia', N'https://localhost:7032/articles/5ccaee38-dd71-4c5b-a830-6f2931727224.webp', 99999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=6)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 8, 1005, 2,       N'VIE-MON-Monitor curvo LED veinticietepulgadas', N'Monitor curvo LED veinticietepulgadas', N'https://localhost:7032/articles/c7d71a0e-8776-4ae2-9458-bd385edbde19.webp', 164999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=8)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 10, 1006, 2,      N'NOB-MON-Monitor LED Panel Va Antiglare veintitrespulgadascomaocho', N'Monitor LED Panel Va Antiglare veintitrespulgadascomaocho', N'https://localhost:7032/articles/f67fcb67-91c8-42c7-b189-66c37dd6c58b.webp', 91999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=10)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1002, 2002, 1002, N'WES-ALM-Disco Solido WD Green docientoscuarenta GB', N'Disco Solido WD Green docientoscuarenta GB', N'https://localhost:7032/articles/63ec83aa-fb16-4de3-b3d0-7bdd13c063e6.webp', 15999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1002)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1004, 2002, 1002, N'WES-ALM-Disco Solido MDOS WD Green DOCIENTOSCUARENTA GB', N'Disco Solido MDOS WD Green DOCIENTOSCUARENTA GB', N'https://localhost:7032/articles/2e0a00b6-f613-467f-b182-6ba825be1d91.webp', 14999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1004)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1006, 2003, 1002, N'HIK-ALM-Disco Solido SSD docientoscuarenta GB', N'Disco Solido SSD docientoscuarenta GB', N'https://localhost:7032/articles/154d495a-3455-4d17-9927-1d0e4aa43b03.webp', 10299, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1006)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1008, 2004, 1002, N'ADA-ALM-Disco Solido SSD Ultimate Docientoscuarenta GB', N'Disco Solido SSD Ultimate Docientoscuarenta GB', N'https://localhost:7032/articles/4bbd3822-349d-43c4-bcf8-f83ea3640a85.webp', 13379, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1008)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1010, 2005, 1002, N'PAT-ALM-Disco Solido SSD cientoveintiocho GB', N'Disco Solido SSD cientoveintiocho GB', N'https://localhost:7032/articles/fdfd45c3-7237-44ae-bbbc-b36b79d4f8fa.webp', 9999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1010)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1012, 2006, 1002, N'LEX-ALM-Disco Solido SSD cientoveintiocho GB', N'Disco Solido SSD cientoveintiocho GB', N'https://localhost:7032/articles/fb7f198f-1b8b-416d-b00c-604f6e4bbb3e.webp', 12490, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1012)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1013, 2007, 1002, N'COR-ALM-Disco Solido MDOS Force Series docientoscuarenta GB', N'Disco Solido MDOS Force Series docientoscuarenta GB', N'https://localhost:7032/articles/eb57c1ce-7d26-47a7-8383-1dac371ad6a6.webp', 36199, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1013)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1014, 2008, 1002, N'GIG-ALM-Disco Solido MDOS cientoveintiocho GB ', N'Disco Solido MDOS cientoveintiocho GB ', N'https://localhost:7032/articles/fa21afeb-e913-4b17-845f-d3db684ab746.webp', 14289, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1014)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1016, 2, 1002,    N'SAM-ALM-Disco Solido SSD Dct Series novecientossesenta GB ', N'Disco Solido SSD Dct Series novecientossesenta GB ', N'https://localhost:7032/articles/4b77deaf-27e8-493f-aa34-7a4e1ec702f9.webp', 328309, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1016)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1018, 2009, 1002, N'KIN-ALM-Disco Solido SSD cuatrocientosochenta GB', N'Disco Solido SSD cuatrocientosochenta GB', N'https://localhost:7032/articles/a11c14e2-dfb8-45f6-8806-c752194d459a.webp', 16496, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1018)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 1020, 2010, 1002, N'CRU-ALM-Disco Solido SSD quinientos GB', N'Disco Solido SSD quinientos GB', N'https://localhost:7032/articles/15bc4a41-6957-41f7-b190-726579c8c386.webp', 16003, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=1020)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2002, 2009, 3002, N'KIN-MEM-Memoria RAM Fury Beast DDRCuatro OCHO GB', N'Memoria RAM Fury Beast DDRCuatro OCHO GB', N'https://localhost:7032/articles/60ceecd7-cf23-406e-93eb-cdf998ad6bff.webp', 13306, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2002)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2004, 2010, 3002, N'CRU-MEM-Memoria RAM Basic dieciseis GB', N'Memoria RAM Basic dieciseis GB', N'https://localhost:7032/articles/0cce6b15-1069-464a-976f-a7458e3c2178.webp', 20890, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2004)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2006, 2007, 3002, N'COR-MEM-memoria RAM Vengeance RGB Pro White treintaydos GB', N'memoria RAM Vengeance RGB Pro White treintaydos GB', N'https://localhost:7032/articles/d4ae0a00-c047-47f8-9393-fccbfc52cf43.webp', 58999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2006)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2008, 2005, 3002, N'PAT-MEM-Memoria RAM Ddrcuatro dieciseis GB', N'Memoria RAM Ddrcuatro dieciseis GB', N'https://localhost:7032/articles/7761b6aa-2427-4b58-9dad-4c386284fb1b.webp', 35000, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2008)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2010, 2009, 3002, N'KIN-MEM-Memoria RAM DDRCuatro Renegade Fury ocho gb', N'Memoria RAM DDRCuatro Renegade Fury ocho gb', N'https://localhost:7032/articles/4b6e02f2-d545-414f-bded-61357bdb6942.webp', 36378, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2010)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2012, 2009, 3002, N'KIN-MEM-Memoria RAM DDRCuatro Impac Fury ocho GB Sodimm', N'Memoria RAM DDRCuatro Impac Fury ocho GB Sodimm', N'https://localhost:7032/articles/1d080bf2-328a-41d3-a198-c5c07d01a1aa.webp', 14949, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2012)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2014, 2009, 3002, N'KIN-MEM-Memoria RAM DDRCuatro Vengeance Rgb Pro Black dieciseis GB', N'Memoria RAM DDRCuatro Vengeance Rgb Pro Black dieciseis GB', N'https://localhost:7032/articles/8ca65c59-a6ff-4709-a53b-72da31ab4709.webp', 76322, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2014)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2016, 1003, 3002, N'HP -MEM-Memoria RAM DDRCuatro VSeis Black ocho GB', N'Memoria RAM DDRCuatro VSeis Black ocho GB', N'https://localhost:7032/articles/ba16a791-d69b-453c-803d-f8f7d692f47a.webp', 27500, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2016)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2018, 1003, 3002, N'HP -MEM-Memoria RAM DDRCuatro VOcho RGB Black dieciseis GB', N'Memoria RAM DDRCuatro VOcho RGB Black dieciseis GB', N'https://localhost:7032/articles/26c68a14-457d-4f60-bb8f-b5ca0e3bfe7f.webp', 37500, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2018)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2020, 2007, 3002, N'COR-MEM-Memoria RAM DDRCuatro Vengeance LPX Black dieciseis GB', N'Memoria RAM DDRCuatro Vengeance LPX Black dieciseis GB', N'https://localhost:7032/articles/6f336f1b-d5fa-47ce-90f7-1efca7282c0f.webp', 38999, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2020)
INSERT INTO [dbo].[Articles] ([Id], [BrandId], [CategoryId], [Code], [Name], [Image], [UnitValue], [Enabled], [Stock])  SELECT 2022, 3002, 3002, N'XPG-MEM-Memoria RAM DDRCuatro XPG Spectrix DCincuenta RGB dieciseis GB', N'Memoria RAM DDRCuatro XPG Spectrix DCincuenta RGB dieciseis GB', N'https://localhost:7032/articles/07efeddd-795f-4055-b45f-0c69b68a09e7.webp', 50323, 1, 0 WHERE NOT EXISTS (SELECT Id FROM Articles WHERE Id=2022)
SET IDENTITY_INSERT [dbo].[Articles] OFF

SET @id = (SELECT ISNULL(MAX(Id),0) FROM ArticlesBrands);
DBCC CHECKIDENT(ArticlesBrands, RESEED, @id)
SET IDENTITY_INSERT [dbo].[ArticlesBrands] ON
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 1,    N'HyperX', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=1)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2,    N'SAMSUNG', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 1002, N'LG ', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=1002)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 1003, N'HP ', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=1003)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 1004, N'PHILIPS', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=1004)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 1005, N'VIEWSONIC', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=1005)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 1006, N'NOBLEX', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=1006)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2002, N'WESTERN DIGITAL', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2002)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2003, N'HIKVISION', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2003)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2004, N'ADATA', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2004)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2005, N'PATRIOT', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2005)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2006, N'LEXAR', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2006)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2007, N'CORSAIR', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2007)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2008, N'GIGABYTE', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2008)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2009, N'KINGSTON', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2009)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 2010, N'CRUCIAL', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=2010)
INSERT INTO [dbo].[ArticlesBrands] ([Id], [Name], [Enabled]) SELECT 3002, N'XPG', 1 WHERE NOT EXISTS (SELECT Id FROM ArticlesBrands WHERE Id=3002)
SET IDENTITY_INSERT [dbo].[ArticlesBrands] OFF

SET @id = (SELECT ISNULL(MAX(Id),0) FROM ArticlesCategories);
DBCC CHECKIDENT(ArticlesCategories, RESEED, @id)
SET IDENTITY_INSERT [dbo].[ArticlesCategories] ON
INSERT INTO [dbo].[ArticlesCategories] ([Id], [Name], [Enabled]) SELECT 2,    N'MONITORES Y PANTALLAS', 1  WHERE NOT EXISTS (SELECT Id FROM ArticlesCategories WHERE Id=2)
INSERT INTO [dbo].[ArticlesCategories] ([Id], [Name], [Enabled]) SELECT 1002, N'ALMACENAMIENTO', 1  WHERE NOT EXISTS (SELECT Id FROM ArticlesCategories WHERE Id=1002)
INSERT INTO [dbo].[ArticlesCategories] ([Id], [Name], [Enabled]) SELECT 3002, N'MEMORIAS RAM', 1  WHERE NOT EXISTS (SELECT Id FROM ArticlesCategories WHERE Id=3002)
SET IDENTITY_INSERT [dbo].[ArticlesCategories] OFF

select * from Articles